# Builds the synthetic fixtures used throughout tests/. Not part of the
# installed package -- see .Rbuildignore.
#
# The generators themselves currently live in tests/testthat/helper-recm.R,
# because the test suite is their only consumer and shipping them as
# package data is roadmap item R-8. This script is the place that R-8 will
# turn into `usethis::use_data(dgp_ecm, dgp_pac)`; keep the two definitions
# in step until then.
#
# Design (docs/04-testing.md, "Fixtures"): a common stochastic trend drives
# a smooth I(1) target and an observed income series with a transitory
# component. Moments are calibrated to Canadian nominal non-durable goods
# consumption and household disposable income -- mean quarterly log growth
# around 0.0104 and 0.0124.
#
# TWO VARIANTS ARE NEEDED AND BOTH MUST BE KEPT:
#
#   dgp_ecm  y generated by a BACKWARD-looking ECM. Tests that the
#            forward-looking specification approximates it -- residuals
#            near white noise. There is no true alpha here.
#
#   dgp_pac  y generated by the ACTUAL PAC rule, with the same alpha the
#            estimator will try to recover. This is the only fixture where
#            parameter recovery is a meaningful test.
#
# Using dgp_ecm for a recovery test is a mistake that looks like a passing
# test.
#
# Why the target is an AR(1) in first differences: it makes the forward sum
# EXACT rather than truncated. With d.ystar_t following an AR(1) with mean
# mu and persistence rho,
#
#     E_{t-1}[d.ystar_{t+i}] = mu + rho^(i+1) (x_{t-1} - mu)
#
# so  Z_t = mu*sum_d + (x_{t-1} - mu) * rho * sum_i d_i rho^i,  and the
# inner sum has the closed form
#
#     sum_i d_i rho^i = A(1)A(beta) iota'(I-G)^{-1}(I - rho G)^{-1} iota
#
# implemented as .dgp_S(). A fixture built from a truncated forward sum
# would not satisfy the Euler equation it is supposed to test.

if (!requireNamespace("devtools", quietly = TRUE)) {
  stop("data-raw/dgp.R needs devtools to load the package sources")
}
devtools::load_all(".", quiet = TRUE)
source("tests/testthat/helper-recm.R")

dgp_pac <- simulate_dgp_pac()
dgp_ecm <- simulate_dgp_ecm()

# Sanity checks the fixtures must satisfy before they are worth shipping.
stopifnot(
  nrow(dgp_pac) == 178L,
  abs(mean(diff(dgp_pac$ystar)) - 0.0104) < 0.003,
  # The exact optimum runs BELOW a growing target (docs/02 section 8).
  mean(dgp_pac$y - dgp_pac$ystar) < 0.02
)

if (FALSE) {
  # TODO(R-8): enable once the datasets are to be shipped, then document
  # them in R/data.R and drop the copies in helper-recm.R.
  usethis::use_data(dgp_ecm, dgp_pac, overwrite = TRUE)
}
