# The invariant tests in this directory are transcribed from
# docs/04-testing.md. They are the specification, not an afterthought.
#
# From CLAUDE.md section 6: never change a test to make code pass. If a test
# fails, either the code is wrong or the mathematics changed. If you believe
# a test is wrong, stop and say so rather than editing it.

# Reference cost weights and discount factor used across several invariant
# tests. Taken from docs/04-testing.md.
.ref_k    <- c(1, 27.6486, 3.2239)
.ref_beta <- 0.98


# ---- synthetic fixtures ----
#
# Mirrors data-raw/dgp.R. Kept here rather than shipped as package data so
# that R-8 stays open and the exported surface does not grow.
#
# TWO VARIANTS, AND THE DIFFERENCE MATTERS:
#
#   simulate_dgp_pac  y generated by the ACTUAL PAC rule with the same
#                     alpha the estimator will try to recover. The only
#                     fixture where parameter recovery is meaningful.
#
#   simulate_dgp_ecm  y generated by a BACKWARD-looking ECM. There is no
#                     true alpha here. Tests only that the forward-looking
#                     specification approximates it.
#
# Moments are calibrated to Canadian nominal non-durable goods consumption
# and household disposable income: mean quarterly log growth around 0.0104
# and 0.0124.

.DGP_N    <- 178
.DGP_G_Y  <- 0.0104
.DGP_RHO  <- 0.5

# sum_i d_i rho^i in closed form: A(1)A(beta) iota'(I-G)^{-1}(I-rho G)^{-1}
# iota. Lets the fixture use the exact forward sum of an AR(1) target
# instead of a truncated one.
.dgp_S <- function(alpha, beta, rho) {
  s <- .scalars(alpha, beta)
  m <- length(alpha)
  drop(s$A1 * s$Ab * s$im %*% s$IGi %*%
         solve(diag(m) - rho * s$G) %*% s$im)
}

simulate_dgp_pac <- function(n = .DGP_N, seed = 20260727, beta = 0.995,
                             k = c(1, 27.6486, 3.2239),
                             measurement_error = FALSE,
                             mu = .DGP_G_Y, rho = .DGP_RHO,
                             sd_u = 0.004, sd_e = 0.002, sd_nu = 0.004) {
  set.seed(seed)
  alpha <- .lq_alpha(k, beta)$alpha
  a <- .alpha_to_a(alpha)
  s <- .scalars(alpha, beta)
  m <- length(alpha)
  S1 <- .dgp_S(alpha, beta, rho)

  nb <- 100L
  N <- n + nb
  u <- stats::rnorm(N, 0, sd_u)
  x <- as.numeric(stats::filter(mu * (1 - rho) + u, rho,
                                method = "recursive", init = mu))
  e <- stats::rnorm(N, 0, sd_e)
  ystar <- cumsum(x)

  y <- numeric(N)
  dy <- numeric(N)
  y[1] <- ystar[1]
  for (tt in 2:N) {
    # E_{t-1}[dystar_{t+i}] = mu + rho^(i+1) (x_{t-1} - mu), so the forward
    # sum is exact rather than truncated.
    Z <- mu * s$sum_d + (x[tt - 1] - mu) * rho * S1
    v <- a[1] * (y[tt - 1] - ystar[tt - 1])
    if (m > 1) {
      for (j in seq_len(m - 1)) {
        v <- v + a[j + 1] * (if (tt - j >= 1) dy[tt - j] else 0)
      }
    }
    dy[tt] <- v + Z + e[tt]
    y[tt] <- y[tt - 1] + dy[tt]
  }

  idx <- (nb + 1L):N
  ystar_obs <- ystar
  if (measurement_error) ystar_obs <- ystar + stats::rnorm(N, 0, sd_nu)

  out <- data.frame(
    y = y[idx],
    ystar = ystar_obs[idx],
    income = cumsum(0.0124 + 0.6 * x + stats::rnorm(N, 0, 0.006))[idx],
    w = stats::rnorm(n, 0, 0.01)
  )
  attr(out, "alpha_true") <- alpha
  attr(out, "a0_true") <- a[1]
  attr(out, "a1_true") <- if (m > 1) a[2] else NA_real_
  attr(out, "beta") <- beta
  out
}

simulate_dgp_ecm <- function(n = .DGP_N, seed = 20260727,
                             a0 = -0.15, a1 = 0.25, cf = 0.6,
                             mu = .DGP_G_Y, rho = .DGP_RHO,
                             sd_u = 0.004, sd_e = 0.002) {
  set.seed(seed)
  nb <- 100L
  N <- n + nb
  u <- stats::rnorm(N, 0, sd_u)
  x <- as.numeric(stats::filter(mu * (1 - rho) + u, rho,
                                method = "recursive", init = mu))
  e <- stats::rnorm(N, 0, sd_e)
  ystar <- cumsum(x)

  y <- numeric(N)
  dy <- numeric(N)
  y[1] <- ystar[1]
  for (tt in 2:N) {
    dy[tt] <- a0 * (y[tt - 1] - ystar[tt - 1]) +
      a1 * (if (tt > 2) dy[tt - 1] else 0) + cf * x[tt] + e[tt]
    y[tt] <- y[tt - 1] + dy[tt]
  }
  idx <- (nb + 1L):N
  data.frame(
    y = y[idx],
    ystar = ystar[idx],
    income = cumsum(0.0124 + 0.6 * x + stats::rnorm(N, 0, 0.006))[idx],
    w = stats::rnorm(n, 0, 0.01)
  )
}

dgp_pac <- simulate_dgp_pac()
dgp_ecm <- simulate_dgp_ecm()
