# Covers recovery on a known DGP, concentration, `subset`, and the
# beta = 1 warning. See docs/04-testing.md.
#
# Recovery is only meaningful on dgp_pac, where y is generated by the
# actual PAC rule with the same alpha the estimator will try to recover.
# Using dgp_ecm for a recovery test is a mistake that looks like a passing
# test -- there is no true alpha to recover.

test_that("beta = 1 warns, and quiet = TRUE suppresses it", {
  expect_warning(
    recm_estimate("y", "ystar", data = dgp_pac, m = 2, var_lags = 2,
                  restarts = 0),
    "beta = 1"
  )
  expect_no_warning(
    recm_estimate("y", "ystar", data = dgp_pac, m = 2, var_lags = 2,
                  restarts = 0, quiet = TRUE)
  )
})

test_that("a missing column is named in the error", {
  expect_error(recm_estimate("nope", "ystar", data = dgp_pac, m = 2,
                             quiet = TRUE),
               "'nope' not found")
  expect_error(recm_estimate("y", "nope", data = dgp_pac, m = 2,
                             quiet = TRUE),
               "'nope' not found")
})

test_that("the estimator is consistent on a known PAC DGP", {
  skip_on_cran()
  # At T = 178 there is a genuine finite-sample downward bias in |a_0| of
  # roughly 0.5 to 0.7 residual standard deviations, measured at var_lags
  # 1, 2 and 4 alike, so it is not VAR over-parameterisation. What IS
  # verified is consistency: the bias goes away as T grows.
  big <- simulate_dgp_pac(n = 4000)
  fit <- recm_estimate("y", "ystar", beta = attr(big, "beta"), data = big,
                       m = 2, var_lags = 4, restarts = 3, quiet = TRUE)
  expect_lt(abs(fit$a[1] - attr(big, "a0_true")), 0.02)
  expect_lt(abs(fit$a_f - fit$scalars$sum_d), 1e-8)
})

test_that("the small-sample bias stays inside one standard deviation", {
  skip_on_cran()
  # Forty replications is enough to catch a real bias and cheap enough for
  # CI; do not turn this into a 1000-replication test. The threshold is 1.0
  # sd rather than the 0.4 sd used as an illustration in docs/04-testing.md
  # because the measured bias/sd on this fixture is 0.51-0.67 -- see the
  # consistency test above.
  a0_true <- attr(dgp_pac, "a0_true")
  MC <- t(vapply(1:40, function(b) {
    d <- simulate_dgp_pac(seed = 500 + b)
    ff <- recm_estimate("y", "ystar", beta = 0.995, data = d, m = 2,
                        var_lags = 2, restarts = 3, quiet = TRUE)
    c(a0 = ff$a[1], a1 = ff$a[2])
  }, numeric(2)))
  expect_lt(abs(mean(MC[, "a0"]) - a0_true), 1.0 * sd(MC[, "a0"]))
  # docs/02 section 10: the standard deviation on a_1 is roughly a_1
  # itself. Assert the order of magnitude, not a point.
  expect_lt(sd(MC[, "a1"]), 3 * abs(attr(dgp_pac, "a1_true")))
})

test_that("the forward-looking rule approximates a backward-looking ECM", {
  # dgp_ecm has no true alpha. The only meaningful claim is that residuals
  # come back near white noise.
  fit <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_ecm, m = 2,
                       var_lags = 2, restarts = 3, quiet = TRUE)
  lb <- Box.test(residuals(fit), lag = 8, type = "Ljung-Box")
  expect_gt(lb$p.value, 0.01)
})

test_that("concentrating out delta recovers the linear coefficient", {
  # delta enters linearly given alpha and is recovered by lm.fit() inside
  # the residual function, keeping Nelder-Mead in 2 dimensions.
  # Concentration is an optimisation device, not an inference shortcut:
  # the full parameter vector is reassembled for the covariance.
  fit <- recm_estimate("y", "ystar", vars = ~ w, beta = 0.995,
                       data = dgp_pac, m = 2, var_lags = 2, restarts = 3,
                       quiet = TRUE)
  expect_length(fit$delta, 1L)
  expect_equal(fit$npar, length(fit$theta) + 1L)
  expect_equal(dim(fit$vcov), c(fit$npar, fit$npar))
  expect_true(is.finite(fit$objective(fit$theta)))
  expect_true("w" %in% names(fit$par))
})

test_that("free_forward adds a_f as a concentrated linear parameter", {
  fit <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 2,
                       var_lags = 2, free_forward = TRUE, restarts = 3,
                       quiet = TRUE)
  expect_true("a_f" %in% names(fit$par))
  # Comparing the freely estimated a_f to sum(d_i) at the estimated alpha
  # is the direct test of the Euler restriction.
  expect_true(is.finite(fit$a_f))
  expect_true(is.finite(fit$scalars$sum_d))
  expect_false(isTRUE(all.equal(fit$a_f, fit$scalars$sum_d)))
})

test_that("subset restricts the estimation sample", {
  full <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 2,
                        var_lags = 2, restarts = 0, quiet = TRUE)
  half <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 2,
                        var_lags = 2, restarts = 0, quiet = TRUE,
                        subset = seq_len(nrow(dgp_pac) %/% 2))
  expect_lt(half$n, full$n)
  expect_equal(half$n, nrow(dgp_pac) %/% 2 - 3L)
})

test_that("restarts do not increase the objective", {
  # Nelder-Mead is not reliable in one pass. Assert on the objective value,
  # not only on the parameters: two very different theta can give nearly
  # identical criteria, which is the whole identification problem.
  one <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 3,
                       var_lags = 2, restarts = 0, quiet = TRUE)
  many <- recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 3,
                        var_lags = 2, restarts = 3, quiet = TRUE)
  expect_lte(many$objective(many$theta), one$objective(one$theta) + 1e-8)
})

test_that("cost = 'free' warns above m = 4", {
  expect_warning(
    recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 6,
                  cost = "free", var_lags = 2, restarts = 0, quiet = TRUE),
    "cost = \"free\""
  )
})

test_that("the growth correction moves the gap toward zero", {
  # On a balanced growth path the exact optimum runs BELOW a growing
  # target; the growth argument removes that by construction. This is a
  # deliberate departure from the exact optimum, matching FRB/US practice.
  d <- dgp_pac
  d$g <- 0.0104
  fit <- recm_estimate("y", "ystar", beta = 0.995, data = d, m = 2,
                       var_lags = 2, growth = "g", restarts = 1,
                       quiet = TRUE)
  expect_true(fit$growth)
  expect_true(all(is.finite(fit$residuals)))
})

test_that("m = 20 estimation stays under 60 seconds", {
  skip_on_cran()
  expect_lt(
    system.time(
      recm_estimate("y", "ystar", beta = 0.995, data = dgp_pac, m = 20,
                    var_lags = 2, restarts = 3, quiet = TRUE)
    )[["elapsed"]],
    60
  )
})
